# Generated by Django 3.2.8 on 2021-10-18 13:52

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogtitle', models.CharField(max_length=500)),
                ('blogdetail', ckeditor.fields.RichTextField()),
                ('blogcreated', models.DateTimeField(auto_now_add=True)),
                ('blogimage', models.FileField(blank=True, null=True, upload_to='BlogImage')),
                ('blogcreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
