# Generated by Django 3.2.8 on 2021-10-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('isbn', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('bookdetail', models.TextField(blank=True, null=True)),
                ('book_image', models.FileField(blank=True, null=True, upload_to='Book Image')),
            ],
        ),
    ]
